### ISSUE TITLE
Buildkite runs not reporting back to GitHub

### ISSUE THREAD

**Issue by tpowell-progress** [chef/mixlib-cli#103]
Buildkite status line is pending and just reads "buildkite/chef-mixlib-cli-main-verify Expected — Waiting for status to be reported" when a community member opens a PR.

@sean-simmons-progress

**Comment by sean-simmons-progress** [comment]
Should be good to go, the repo has been added to the list for buildkite. 

<img width="332" alt="image" src="https://github.com/chef/mixlib-cli/assets/111799713/4bc4c52b-97aa-420c-8231-704bef498f1e">
