### ISSUE TITLE
config settings no longer set from proc

### ISSUE THREAD

**Issue by mwrock** [chef/mixlib-cli#29]
When chef's mixlib-cli dependencies were bumped to the latest of this gem, we began seeing the below unit test failure in jenkins:
```
  1) Chef::Knife::Bootstrap specifying no_proxy with various entries via --ssl-verify-mode none renders the client.rb with ssl_verify_mode set to :verify_none
     Failure/Error: expect(rendered_template).to match(/ssl_verify_mode :verify_none/)

       expected "bash -c '\nlog_location     STDOUT\nchef_server_url  \"https://localhost:443\"\nvalidation_client_name \"chef-validator\"\n# Using default node name (fqdn)\n'" to match /ssl_verify_mode :verify_none/
       Diff:
       @@ -1,2 +1,7 @@
       -/ssl_verify_mode :verify_none/
       +bash -c '
       +log_location     STDOUT
       +chef_server_url  "https://localhost:443"
       +validation_client_name "chef-validator"
       +# Using default node name (fqdn)
       +'

     # ./spec/unit/knife/bootstrap_spec.rb:326:in `block (4 levels) in <top (required)>'

Finished in 0.0285 seconds (files took 4.39 seconds to load)
1 example, 1 failure
```

In my attempt to fix it I submitted: https://github.com/chef/chef/pull/5099 but closed it when I realized it was related to bumping this gem and I just removed the bump.

I think this is related to @coderanger 's https://github.com/chef/mixlib-cli/commit/b7043c598293bfd74fbbfa7a9ce9edc4c2724c03 commit.

**Comment by coderanger** [comment]
Following up, I think this was fixed by https://github.com/chef/chef/commit/b50d7dd216c51f7b3aa09b4c3f2bc4031a60344e

**Comment by mwrock** [comment]
cool I'll validate that in our acceptance tests and report back in the next couple days.

**Comment by mwrock** [comment]
See https://github.com/chef/chef-dk/pull/961#issuecomment-237998771

**Comment by coderanger** [comment]
Again, this was fixed in Chef, chef-dk is just linked to an old version of the chef gem.
