### ISSUE TITLE
[Feature Request] Multi-line description ?

### ISSUE THREAD

**Issue by rockandska** [chef/mixlib-cli#37]
Hi,

Is there any reliable solution to write multi-line description ?
I don't find anything about this possibility
Only find an old fork who implemented it [this way](https://github.com/dreamcat4/mixlib-cli/blob/4496ee1be718ea08626e4ed9ab998bf2846927cc/lib/mixlib/cli.rb#L553-L571)

Regards,

**Comment by majormoses** [comment]
I think you should be able to use a heredoc

**Comment by tas50** [comment]
Closing this since a heredoc is the way to do this
