### ISSUE TITLE
1.7.7 release drops support for Ruby 2.4 and below

### ISSUE THREAD

**Issue by skewart** [chef/mixlib-cli#55]
# Version:

1.7.7

# Environment: Ruby 2.4

# Scenario:

Install mixlib-cli

# Steps to Reproduce:

Install mixlib-cli version 1.7.7 in an environment using Ruby 2.4

# Expected Result:

mixlib-cli should be installed and work just fine.

# Actual Result:

Can't install because it requires Ruby >= 2.5.    

It looks like 1.7.7 accidentally got released with the Ruby 2.5 requirement that was meant to only go out with a major version bump.   It caused problems on our systems that are running Ruby 2.4 and depend on cookbooks that depend on mixlib-cli ~>1.7.   We pinned everything at 1.7.6, but I'm guessing other folks will run into the same problem.

**Comment by ascot21** [comment]
Can we just get a 1.7.8 version tag that has the minimum ruby version set to 2.4? Then you can leave 2.0.0 as requiring ruby 2.5.

**Comment by skewart** [comment]
Turns out our problem was slightly different - our dependency actually floated up to your 2.0.0 release thanks to a third-party library importing mixlib-cli that wasn't properly locked down. So, I'm closing this issue because it's not really an issue on your end.  Sorry for the false alarm!

**Comment by tas50** [comment]
Glad you got to the bottom on this one. I was a bit confused how that change was impacting you that way.
