### ISSUE TITLE
Request: Push patch releases of 1.7.X to Rubygems

### ISSUE THREAD

**Issue by cmparkinson** [chef/mixlib-cli#57]
Would it be possible to get the patch version releases of 1.7.X pushed to Rubygems?  We're hitting a snag with 1.7.0 related to frozen strings, which was fixed in 1.7.1 with this PR:  https://github.com/chef/mixlib-cli/pull/34.

Jumping to >= 2.0.0 isn't possible due to support for ruby < 2.5 being dropped.

**Comment by tas50** [comment]
@cmparkinson not sure if it helps but I added back Ruby 2.4 support in 2.0.3

**Comment by cmparkinson** [comment]
:man_facepalming: Yes, yes it does.  My bad for only reading the breaking changes in 2.0.0 and not continuing to read.

Thanks for the quick response!

**Comment by tas50** [comment]
We quickly realized we went way to far deprecating ruby releases and it not only caused community pain, but pain to ourselves.
