### ISSUE TITLE
Releases on rubygems.org

### ISSUE THREAD

**Issue by grawlinson** [chef/mixlib-cli#82]
The last two releases (`2.1.9` and `2.1.10`) don't seem to show up on [rubygems](https://rubygems.org/gems/mixlib-cli).

**Comment by tas50** [comment]
That's by design. Our builds tooling bumps and tags every version, but only promotes on command. If you check the changelog it says "Changes not yet released to rubygems.org" above those versions. There's not a real point in pushing that minor change at this time.
